[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[context.production]
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
